### ISSUE TITLE
Feature request: macro-% for 'pastie site'

### ISSUE THREAD

**Issue by justinsteven** [xme/pastemon#1]
Just an idea (I'm not a programmer, or I'd do it myself :3) would it be possible to have a macro-% for the dump directory pathing that is the name of the pastie site that the pastie was downloaded from?

It would be nice to have paths like:
2012/10/22/pastebin.com/
2012/10/22/pastie.org/
etc.

Cheers!

**Comment by xme** [comment]
Thank for the feedback!
That's a great idea indeed. Added to my todolist!

/x

## 

Can't sleep, hackers will eat me!
PGP Key: http://pgp.mit.edu:11371/pks/lookup?op=get&search=0x42D006FD51AD7F2C

**Comment by xme** [comment]
Code added!
'%S' has been added to be replaced by the site name.
Will commit asap.

**Comment by justinsteven** [comment]
Fantastic. Many thanks Xavier!

**Comment by xme** [comment]
Commited!
