### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Zowlex** [xme/pastemon#2]
DBI::db=HASH(0x55a42c0252c0)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at ./pastemon.pl line 761.
pastemon.pl already running (PID 3774) at ./pastemon.pl line 168.

I tried closing the statement but it didn't work, I'm kinda new to programming !

**Comment by xme** [comment]
Why do you run two concurrent processes? If you do this, try to not use the same db. Otherwise, I never had this error before.

**Comment by Zowlex** [comment]
This error happens when I type "sudo perl pastemon.pl" to run the program .Am I missing something ?
